version: '3.8'

services:
  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - auth-service
      - user-service
      - product-service
      - order-service
      - review-service
      - rabbitmq
    networks:
      - my_network

  auth-service:
    build: 
      context: ./src/services/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/my-microservice
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - my_network

  user-service:
    build: 
      context: ./src/services/user-service
      dockerfile: Dockerfile
    container_name: user-service
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/my-microservice
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - my_network

  product-service:
    build: 
      context: ./src/services/product-service
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/my-microservice
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - my_network

  order-service:
    build: 
      context: ./src/services/order-service
      dockerfile: Dockerfile
    container_name: order-service
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/my-microservice
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - my_network

  review-service:
    build: 
      context: ./src/services/review-service
      dockerfile: Dockerfile
    container_name: review-service
    environment:
      - NODE_ENV=development
      - MONGO_URL=mongodb://mongo:27017/my-microservice
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my_network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
